version: "2"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocritic
    - revive
    - nilaway

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

issues:
  exclude-use-default: false
